<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Birds.hbm.xml" />
    <None Remove="hibernate.cfg.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Birds.hbm.xml" />
    <EmbeddedResource Include="hibernate.cfg.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NHibernate" Version="5.5.2" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.0" />

  </ItemGroup>

</Project>
